language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)
  - mkdir -p ~/quicklisp/dists/digikar99
  - ls -l ~/quicklisp/dists

script:
  - cl --eval '(progn
                 (defun ql-dist::dist-name-pathname (name)
                   "Return the pathname that would be used for an installed dist with
                    the given NAME."
                  (ql-dist::qmerge
                   (make-pathname :directory (list* :relative "dists"
                                                    (uiop:split-string name :separator "/")))))
                 (defun digikar99-dist-enumeration-function ()
                   "The default function used for producing a list of dist objects."
                   (loop for file
                       in (directory (ql-dist::qmerge "dists/digikar99/*/distinfo.txt"))
                     collect (ql-dist::make-dist-from-file file)))
                 (push (quote digikar99-dist-enumeration-function)
                       ql::*dist-enumeration-functions*)
                 (ql-dist:install-dist
                  "http://dist.ultralisp.org/digikar99/specialized-array-dispatch.txt"
                  :prompt nil)
                 (push :travis *features*)
                 (ql:quickload "adhoc-polymorphic-functions")
                 (uiop:quit 0))'
  - cl --eval '(progn
                 (defun ql-dist::dist-name-pathname (name)
                   "Return the pathname that would be used for an installed dist with
                    the given NAME."
                  (ql-dist::qmerge
                   (make-pathname :directory (list* :relative "dists"
                                                    (uiop:split-string name :separator "/")))))
                 (defun digikar99-dist-enumeration-function ()
                   "The default function used for producing a list of dist objects."
                   (loop for file
                       in (directory (ql-dist::qmerge "dists/digikar99/*/distinfo.txt"))
                     collect (ql-dist::make-dist-from-file file)))
                 (push (quote digikar99-dist-enumeration-function)
                       ql::*dist-enumeration-functions*)
                 (push :travis *features*)
                 (ql:quickload "adhoc-polymorphic-functions")
                 (asdf:test-system :adhoc-polymorphic-functions)
                 (uiop:quit 0))'

notifications:
  email: false
